// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v4.24.3
// source: commons/proto/sign.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Sign struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AugMessage []byte `protobuf:"bytes,1,opt,name=aug_message,json=augMessage,proto3" json:"aug_message,omitempty"`
}

func (x *Sign) Reset() {
	*x = Sign{}
	if protoimpl.UnsafeEnabled {
		mi := &file_commons_proto_sign_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sign) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sign) ProtoMessage() {}

func (x *Sign) ProtoReflect() protoreflect.Message {
	mi := &file_commons_proto_sign_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sign.ProtoReflect.Descriptor instead.
func (*Sign) Descriptor() ([]byte, []int) {
	return file_commons_proto_sign_proto_rawDescGZIP(), []int{0}
}

func (x *Sign) GetAugMessage() []byte {
	if x != nil {
		return x.AugMessage
	}
	return nil
}

var File_commons_proto_sign_proto protoreflect.FileDescriptor

var file_commons_proto_sign_proto_rawDesc = []byte{
	0x0a, 0x18, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x73, 0x69, 0x67, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x27, 0x0a, 0x04, 0x53, 0x69, 0x67, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x75, 0x67,
	0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a,
	0x61, 0x75, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x64, 0x75, 0x61, 0x72, 0x64, 0x6f,
	0x6e, 0x75, 0x6e, 0x65, 0x73, 0x70, 0x2f, 0x62, 0x6c, 0x73, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_commons_proto_sign_proto_rawDescOnce sync.Once
	file_commons_proto_sign_proto_rawDescData = file_commons_proto_sign_proto_rawDesc
)

func file_commons_proto_sign_proto_rawDescGZIP() []byte {
	file_commons_proto_sign_proto_rawDescOnce.Do(func() {
		file_commons_proto_sign_proto_rawDescData = protoimpl.X.CompressGZIP(file_commons_proto_sign_proto_rawDescData)
	})
	return file_commons_proto_sign_proto_rawDescData
}

var file_commons_proto_sign_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_commons_proto_sign_proto_goTypes = []interface{}{
	(*Sign)(nil), // 0: proto.Sign
}
var file_commons_proto_sign_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_commons_proto_sign_proto_init() }
func file_commons_proto_sign_proto_init() {
	if File_commons_proto_sign_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_commons_proto_sign_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sign); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_commons_proto_sign_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_commons_proto_sign_proto_goTypes,
		DependencyIndexes: file_commons_proto_sign_proto_depIdxs,
		MessageInfos:      file_commons_proto_sign_proto_msgTypes,
	}.Build()
	File_commons_proto_sign_proto = out.File
	file_commons_proto_sign_proto_rawDesc = nil
	file_commons_proto_sign_proto_goTypes = nil
	file_commons_proto_sign_proto_depIdxs = nil
}
